name: move_on_app
description: "A fitness app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  auto_route: ^9.3.0+1
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  forui: ^0.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  modal_bottom_sheet: ^3.0.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
